name: CI for Solidity Contracts

on:
    push:
        branches:
            - master
    pull_request:
        types: [opened, synchronize, reopened]

jobs:
    build:
        uses: The-Poolz/solidity-workflows/.github/workflows/build.yml@v0.6.0
        secrets:
            codecov_token: ${{ secrets.CODECOV_TOKEN }}